// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BackendAndAPI.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BackendAndAPI.Models
{
    public partial interface IMSSQLLocalDBContextProcedures
    {
        Task<int> AddUserAsync(string Name, int? Height, int? Weight, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAllUsersResult>> GetAllUsersAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
