// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.DAL.OutDto;

public partial class Company
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Code { get; set; }
}