// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API.DAL.OutDto;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace API.DAL.Context
{
    public partial class DatabaseContext
    {
        private DatabaseContextProcedures _procedures;

        public virtual DatabaseContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new DatabaseContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public DatabaseContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AddUserResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<GetAllUsersResult>().HasNoKey().ToView(null);
        }
    }

    public interface IDatabaseContextProceduresContract
    {
        Task<int> AddUserAsync(string Name, int? Height, int? Weight, CancellationToken cancellationToken = default);
        Task<List<GetAllUsersResult>> GetAllUsersAsync(CancellationToken cancellationToken = default);
    }

    public partial class DatabaseContextProcedures
    {
        private readonly DatabaseContext _context;

        public DatabaseContextProcedures(DatabaseContext context)
        {
            _context = context;
        }

        public virtual async Task<int> AddUserAsync(string Name, int? Height, int? Weight, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Name",
                    Size = 40,
                    Value = Name ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Height",
                    Value = Height ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Weight",
                    Value = Weight ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[AddUser] @Name, @Height, @Weight", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<GetAllUsersResult>> GetAllUsersAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetAllUsersResult>("EXEC @returnValue = [dbo].[GetAllUsers]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
